### ISSUE TITLE
Problem with running .exe

### ISSUE THREAD

**Issue by DazzaSazza** [OniSensei/Gotcha-v2.1#13]
It wont let me run the "Gotcha v2.1" application. I am running on Windows 10 at the moment.
It says...
"Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw and exception. ---> System.InvalidCastException: Conversion from string "8/13/2019 3:04:28 PM" to type 'Date' is not valid.
        at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
        at Gotcha_v2._1.Gotcha . . cctor ()
        --- End of inner exception stack trace ---
        at Gotcha_v2._1.Gotcha.Main(String[] args)
"

**Comment by OniSensei** [comment]
this is because there is a file that uses US date and time formatting
which is 12hour clock with AM  PM and M/DD/YYYY date formatting
so
you need to opn bot folder, open config folder, then open levels with a text editor
then change the date / time in there to match your countries format
