### ISSUE TITLE
Autovoter not working??

### ISSUE THREAD

**Issue by CPM2486** [OniSensei/Gotcha-v2.1#18]
I configured the voter.ini file and I filled it with my discord account, but every time the bot opens chrome, when it's trying to log in it crashes
[160919114144_log.txt](https://github.com/OniSensei/Gotcha-v2.1/files/3615617/160919114144_log.txt)

**Comment by KingDarnit** [comment]
hey, so the voter doesnt really work for now because of some changes in discord api i think. just disable it.

**Comment by KingDarnit** [comment]
close this issue please. oni will probably be able to fix this eventually sometime in the future when he has the chance.

**Comment by CPM2486** [comment]
oh, yep, sorry
