### ISSUE TITLE
Auto-catch no longer works

### ISSUE THREAD

**Issue by HubSub3** [OniSensei/Gotcha-v2.1#19]
The auto-spam continues to work as before, but the last time the auto-catch worked for me was late on September 21.  I checked the config files and also removed the bot and set it up again, but it didn't fix the issue.

**Comment by Kant-dev** [comment]
There are rumours that discord or pokecord did something to prevent autocatchers. Should we hope for it to work or is it permanent? Waiting for a reply from the developer...

**Comment by KingDarnit** [comment]
nah the rumors are fake, doesnt really work like that. i never got much error logs so not sure what happened but pretty sure oni can fix it cuz he a big brain fella.

so no worries, also pls dont fill defaults dms as hes been working on a project called poke egg and i dont think he wants to be bothered lol. if u want, u can check it out here https://discordbots.org/bot/612522371701538817

**Comment by KingDarnit** [comment]
close this issue please. oni will fix it when he has time.
