### ISSUE TITLE
Didn't Get The Bot

### ISSUE THREAD

**Issue by sivvy4402** [OniSensei/Gotcha-v2.1#23]
I paid $5 on the patreon and didn't receive anything from the creator.
I'm still waiting to be friended by him on the discord, can't send him dms because my friend request is not accepted yet.
Sorry for the bothersome post though. :(

**Comment by zettu** [comment]
did you ever get it @sivvy4402 @OniSensei id like to get it

**Comment by OniSensei** [comment]
Make sure you add and send me a message, I was recently in a bad accident and just recently got out of the hospital.

**Comment by nameless695** [comment]
@OniSensei I donated 2 days ago and sent request in discord, but can't send a message there, and didn't receive the bot yet ;-;

**Comment by OniSensei** [comment]
@sivvy4402 please be sure to send me a message on discord otherwise i wont know why you added me.

@zettu same thing

@nameless695 same thing you should be able to message me now
