### ISSUE TITLE
Whats your paypal so i can domate for the bot? :))

### ISSUE THREAD

**Issue by zettu** [OniSensei/Gotcha-v2.1#25]
do you also have something for trading

**Comment by OniSensei** [comment]
nothing for tradeing and u can use the donatebot.io checkout to donate to my paypal.
https://donatebot.io/checkout/627563468035194881

**Comment by Purg25** [comment]
you know i love how your info says min to donate is 1$ but when clicking on that donatebot.io it wants a min of 2$ a month. think maybe you could be a little more transparent about what you actually want? that'd be alot nicer also i'd rather the paypal option then a donatebot myself. i don't feel like giving discord my financial information.

**Comment by OniSensei** [comment]
@Purg25 
updates are posted to the reddit page and not here.

https://www.reddit.com/r/gotchabot/comments/ep8agu/gotcha_bot_premium_now_subscription_based/
