### ISSUE TITLE
New update crashes

### ISSUE THREAD

**Issue by y34ujsdfm** [OniSensei/Gotcha-v2.1#3]
It was working before and then it tries to update and crashes the cmd.
![image](https://user-images.githubusercontent.com/53682112/62419669-b7d41a00-b63a-11e9-8d75-e25b912a7409.png)

**Comment by OniSensei** [comment]
Open /config/version.ini and change Version to 2.1.0.9

Apologies I forgot to update the setting before uploading. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OniSensei** [comment]
Actually i looked at the release and the file is fine. 

Please make sure you extract the entire zip and overwrite any existing files. If this keeps happening we can investigate further, but a temporary fix is to the the AutoUpdater = False.

**Comment by y34ujsdfm** [comment]
I went into config/updater.ini and changed it from 2.1.0.8 to 2.1.0.9 and it worked perfectly. Thank you!
