### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AridStarfish** [OniSensei/Gotcha-v2.1#5]
Not Working

**Comment by OniSensei** [comment]
Is love to help you but I need more information than that.

Care to message me on discord?
DefaulT#2648

**Comment by Proteev** [comment]
i have something to say my cmd says that Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nini, Version=1.1.0.0, Culture=neutral, PublicKeyToken=691faec150a7fa7b' or one of its dependencies. The system cannot find the file specified.
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)
 i dont understand how to fix this

**Comment by OniSensei** [comment]
Somehow you’re missing nini.dll
Download the latest version of the bot here 
https://github.com/OniSensei/Gotcha-v2.1/releases/download/2.1.1.1/Gotcha.Bot.v2.1.1.1.zip

**Comment by phiny25** [comment]
i have the same problem :(

**Comment by OniSensei** [comment]
missing nini? follow the use the link i provided and make sure your anti virus isnt deleting it for some reason

**Comment by phiny25** [comment]
i press gotcha v2.1 exe and 3 sec then the programme close

**Comment by phiny25** [comment]
and i have nini.dll

**Comment by OniSensei** [comment]
Screen shot the error and make your own issue please

**Comment by Proteev** [comment]
onisenesei the same problem

**Comment by Proteev** [comment]
idk how to fix the nini

**Comment by ArchCrypto712** [comment]
> and i have nini.dll

I have the nini.dll too and its still giving me this error message Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception

**Comment by OniSensei** [comment]
Move the entire bot folder “Gotcha v2.1” to your appdata/local folder.

**Comment by ArchCrypto712** [comment]
How to change the keybind to pause and resume the programme because to
pause and resume i have to press Fn+F12 and that also opens developer tools
on chrome.

**Comment by OniSensei** [comment]
Make your own issue thread and stop posting on closed one. 

O read the readme for how to change the hotkey.
