### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by Lucifer-morningstar-1** [OniSensei/Gotcha-v2.1#6]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.InvalidCastException: Conversion from string "8/13/2019 3:04:28 PM" to type 'Date' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)

**Comment by OniSensei** [comment]
***How to fix date time format error***
Press windows key
Search for Control Panel
Open Control Panel
Click Region
Change format to English (United States)

This will be fixed in v2.1.1.2
