### ISSUE TITLE
Auto Catcher not working

### ISSUE THREAD

**Issue by nikgk1215** [OniSensei/Gotcha-v2.1#7]
When a pokemon is apears, the bot does not recognize the pokemon and it just says the "[ENCOUNTERED]" message

**Comment by OniSensei** [comment]
Does the bot spam text? Or no?

**Comment by nikgk1215** [comment]
yeah it does that

**Comment by OniSensei** [comment]
interesting, add me on discord lets see if we can figure it out 
Default#2648

**Comment by nikgk1215** [comment]
your name didnt work

**Comment by OniSensei** [comment]
Sorrry DefaulT#2648
