### ISSUE TITLE
My problem

### ISSUE THREAD

**Issue by Proteev** [OniSensei/Gotcha-v2.1#8]
having a problem saying  Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nini, Version=1.1.0.0, Culture=neutral, PublicKeyToken=691faec150a7fa7b' or one of its dependencies. The system cannot find the file specified.
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)

**Comment by Proteev** [comment]
here is the screenshot

**Comment by Proteev** [comment]
![Capture](https://user-images.githubusercontent.com/54142175/63222375-c38e1780-c1c8-11e9-9cc2-2922e7338f36.PNG)

**Comment by Proteev** [comment]
you can also add me on discord Proteev#3645

**Comment by OniSensei** [comment]
Make sure nini.dll is in the same folder as the bot.
